//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;

namespace DotNetNuke.Modules.ActiveForums
{

	public partial class ActiveForumViewerSettings
	{

		///<summary>
		///drpForumInstance control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.DropDownList drpForumInstance;

		///<summary>
		///drpForum control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.DropDownList drpForum;

		///<summary>
		///drpForumViewTemplate control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.DropDownList drpForumViewTemplate;

		///<summary>
		///drpTopicsTemplate control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.DropDownList drpTopicsTemplate;

		///<summary>
		///drpTopicTemplate control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.DropDownList drpTopicTemplate;
	}
}
