//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;

using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using DotNetNuke;

namespace DotNetNuke.Modules.ActiveForums
{

	public partial class af_searchquick
	{

		///<summary>
		///tblSearch control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.HtmlControls.HtmlTable tblSearch;

		///<summary>
		///lblSearch control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.Label lblSearch;

		///<summary>
		///txtSearch control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.TextBox txtSearch;

		///<summary>
		///lnkSearch control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.LinkButton lnkSearch;
	}
}
