//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;

namespace DotNetNuke.Modules.ActiveForums
{

	public partial class profile_adminsettings
	{

		///<summary>
		///adminrow1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.HtmlControls.HtmlTableRow adminrow1;

		///<summary>
		///txtRewardPoints control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.TextBox txtRewardPoints;

		///<summary>
		///txtUserCaption control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.TextBox txtUserCaption;

		///<summary>
		///chkDisableSignature control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.CheckBox chkDisableSignature;

		///<summary>
		///chkDisableAvatar control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.CheckBox chkDisableAvatar;

		///<summary>
		///drpDefaultTrust control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.DropDownList drpDefaultTrust;

		///<summary>
		///chkMonitor control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.CheckBox chkMonitor;

		///<summary>
		///chkDisableAttachments control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.CheckBox chkDisableAttachments;

		///<summary>
		///btnAdminSave control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::DotNetNuke.Modules.ActiveForums.Controls.ImageButton btnAdminSave;

		///<summary>
		///btnAdminCancel control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::DotNetNuke.Modules.ActiveForums.Controls.ImageButton btnAdminCancel;

		///<summary>
		///cbAdmin control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::DotNetNuke.Modules.ActiveForums.Controls.Callback cbAdmin;
	}
}
